export const cars = [
    {
        id: 1,
        label: 'AUDI',
        model: 'tt',
        power: 2,
        year: 2005,
        prise: 22000,
        color: 'red',
    },
    {
        id: 2,
        label: 'BMW',
        model: 'x6',
        power: 3,
        year: 2009,
        prise: 32000,
        color: 'white',
    },
    {
        id: 3,
        label: 'MAZDA',
        model: '3',
        power: 1.6,
        year: 2010,
        prise: 12000,
        color: 'blue',
    },
    {
        id: 4,
        label: 'OPEL',
        model: 'astra',
        power: 1.8,
        year: 2009,
        prise: 32000,
        color: 'green',
    },
    {
        id: 5,
        label: 'RENAUL',
        model: 'logan',
        power: 1.4,
        year: 2020,
        prise: 26000,
        color: 'white',
    },
];